### ISSUE TITLE
Drawio format compatibility for migration?

### ISSUE THREAD

**Issue by romanr** [sindrel/excalidraw-converter#13]
Was hoping this tool would help to move form Excalidraw to drawio. Saved few diagrams from Excalidraw and none of them opened in drawio, all failed. 
Diagrams seem to be open in Gliffy, but can't use Gliffy to migrate because it does not export to file with trial. To export to Google drive it asks for upgrade.   
Is there anything I am missing , maybe there's some other way?

**Comment by sindrel** [comment]
Hi @romanr,

Do you get any error messages when attempting to open them in draw.io?

I tried reproducing the issue:

1. By importing a converted Excalidraw diagram in Gliffy format in the web version of draw.io ([diagrams.net](https://app.diagrams.net)), and it seemed to open without issues.

2. By importing the Gliffy file from the test suite ([here](https://github.com/sindrel/excalidraw-converter/blob/master/test/data/test_output.gliffy)), this also seemed to work fine.

![image](https://github.com/sindrel/excalidraw-converter/assets/35308882/fdf8d7b3-5866-47fa-8b20-c13a8ba99eca)

**Comment by sindrel** [comment]
Closed due to in
