### ISSUE TITLE
BUg : drawio import doesn't works

### ISSUE THREAD

**Issue by theoberthier** [sindrel/excalidraw-converter#43]
**Describe the bug**

after converstion of file, i import my file in drawio and i have this error : 
"N'est pas un fichier de diagramme (error on line 1 at column 1: Start tag expected, '<' not found)"

**To Reproduce**
Take latest realese for linux amd 64 and convert excalidraw file. and import in drawio file

![image](https://github.com/user-attachments/assets/8280c18a-e685-4f8f-abda-f895f0ea66c5)

**Runtime environment (please complete the following information):**
 - OS: Ubuntu linux 22.04

**Comment by sindrel** [comment]
Hi @theoberthier! Do you get the same error if you try to import it in the online version of [draw.io](https://app.diagrams.net/)?

**Comment by sindrel** [comment]
Thanks for providing the answer to this, @ymartin59. Much appreciated!

Gliffy diagrams are not supported in the desktop version, as noted in [this official draw.io blog post](https://www.drawio.com/blog/import-gliffy-online). An explanation to why is provided in [this GitHub issue](https://github.com/jgraph/drawio-desktop/issues/688).

I'll make sure to clarify this in the docs.
